### PR TITLE
LEXI-64 Create ClayModal

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @carloslancha, please review and merge if you're satisfied... I think from now on you and @matuzalemsteles can review and merge each other's PRs, no need for me to weigh in unless you have a specific question 😉

**Comment by carloslancha** [comment]
@jbalsas I think we have no permissions... 😅

**Comment by brunobasto** [comment]
I have just invited both of you @carloslancha and @matuzalemsteles

**Comment by jbalsas** [comment]
I'm merging this for now, just to keep it moving and see if we can address the teams needs for updating to BS4 in https://github.com/metal/metal-modal/pull/17

Feel free to review afterwards so we can put the final touches!

**Comment by carloslancha** [comment]
Thx @jbalsas ! I'll try to take a final look tomorrow :)

**Pull request merged**
