### PR TITLE
Normalize Button STATE properties

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by fernandosouza** [comment]
Thx @Robert-Frampton 
LGTM

**Review by fernandosouza — APPROVED** [review]

**Review by brunobasto — APPROVED** [review]
LGTM

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Hey @Robert-Frampton,

The changes look good, but I'm getting some errors when running lerna run test or even gulp test inside the module. I also get the same errors on master without your changes. Maybe I"m forgetting to build something..

**Comment by brunobasto** [comment]
ERROR: 'The property called "symbol" is required but didn't receive a value.'
ERROR: 'The property called "symbol" is required but didn't receive a value.'
ERROR: 'The property called "spritemap" is required but didn't receive a value.'
ERROR: 'The property called "spritemap" is required but didn't receive a value.'

and 

 Uncaught Error: Could not find module '../../metal-quartz-icon/src/MetalQuartzIcon' from '/Users/brunobasto/Projects/metal-quartz-components/packages/metal-quartz-button/src/MetalQuartzButton.js'
  at node_modules/karma-commonjs/client/commonjs_bridge.js:85

**Comment by fernandosouza** [comment]
Hey, @brunobasto. I think the `symbol` and `spritemap` error is related to this validation in soy file.

https://github.com/metal/metal-quartz-components/blob/master/packages/metal-quartz-button/src/MetalQuartzButton.soy#L36

These attributes are required for the `icon` component and somehow we are trying to instantiate it without passing its values.

I'm going to fix it.

**Comment by fernandosouza** [comment]
@brunobasto, are you sure that those `symbol` and `spritemap` errors come from the button component? I see them only from the `icons` component.

**Comment by fernandosouza** [comment]
It seems that the `import` issue is related to the `karma` process context. The process cannot access parent directories. I think we have to do something like [`metal.js`](https://github.com/metal/metal.js) does, configuring karma to run the test in the root directory.

@Robert-Frampton. Have you got thoughts about it?

**Comment by robframpton** [comment]
Hey @fernandosouza 

I'm fine with running it from the root directory. I think it will save us from running into a lot of other issues. My one questions is if we'll be able to run just the tests of a specific component.

For example, if I'm working on the button component, I want to be ale to run just the button tests while I'm working on it, and not have to run all tests in the repo.

**Comment by fernandosouza** [comment]
Yeah. It would be great if we could run just the tests of a specific component, but doing that way it isn't possible.

We could use the way Metal.js does and make improvements later. The way tests are implemented now we are not able to integrate other Quartz components once Learn applies symbolic links.

cc. @brunobasto

**Comment by robframpton** [comment]
@fernandosouza ok, sounds good to me then. I went ahead and merged this one. I created #16 for furthering the discussion.

**Pull request merged**
