### PR TITLE
Metal Quartz Link: remove html attribute

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Review by brunobasto — APPROVED** [review]

**Comment by jbalsas** [comment]
Hey @fernandosouza, @brunobasto, @Robert-Frampton, what was the reason for this?

**Comment by fernandosouza** [comment]
Hey, @jbalsas. Should the component allow render an entire link element from a string once the template is in charge of that? My suggestion with this pull request is let the template responsible of what is being rendered. Does it make sense?

**Comment by jbalsas** [comment]
Makes sense, yeah!

**Comment by fernandosouza** [comment]
Awesome! I'm going to rebase and resend. 😃

**Comment by jbalsas** [comment]
Cool!

I just merged https://github.com/metal/metal-clay-components/pull/41 removing the`metal-` prefix, so please, rebase on top of that one! :)

**Pull request closed without merging**
