### PR TITLE
Remove size lg and xl in sticker

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Hey guys,

Patrick updated the sticker sizes and now only has `sm` and default.

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey! We need to find out a way to be coordinated with things like this, because right now Lexicon documentation still defines 4 sizes... https://issues.liferay.com/browse/LEXI-90

**Comment by matuzalemsteles** [comment]
Hey @carloslancha,

I agree with you, Patrick is updating some things based on the lexicon documentation, I can not tell if are having some mismatch of documentation or are not being updated. I'am check!

**Comment by pat270** [comment]
@carloslancha agreed also, I told @matuzalemsteles that lg and xl were removed because I only saw two sizes on the Invision master file.

**Comment by carloslancha** [comment]
I'll talk with them tomorrow to find a solution. Thx guys!

**Comment by victorvalle** [comment]
Hi @pat270 & @matuzalemsteles ! I'm sorry to tell you that we have 4 sizes defined in the documentation but the invision was not updated. Now it is updated. Please bring back the 2 sizes removed.

**Comment by matuzalemsteles** [comment]
@victorvalle Thanks.

Pr closed.

**Pull request closed without merging**
