### PR TITLE
Metal Quartz Link: remove html attribute

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Review by robframpton — APPROVED** [review]
LGTM

**Comment by jbalsas** [comment]
There's one failing test, @fernandosouza! No-one escapes the Big Brother Travis now 😂

**Comment by fernandosouza** [comment]
I'm going to take a look, @jbalsas. :)

**Comment by fernandosouza** [comment]
@jbalsas, now it is fine. :)

**Pull request merged**
