### PR TITLE
Metal Quartz Link: remove html attribute

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by robframpton** [comment]
Due to f8abd7353e707302accfe8f6e644f3705ae98d61 this pr needs to be rebased.

**Comment by brunobasto** [comment]
@fernandosouza Can you rebase this one and resend?

**Comment by fernandosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fernandosouza** [comment]
Resent https://github.com/metal/metal-clay-components/pull/33

**Pull request closed without merging**
