### PR TITLE
ClayCards

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
Hey @carloslancha, **ClayRadio** is not implemented, we would have to change the API, any idea about this?

**Comment by carloslancha** [comment]
@matuzalemsteles I talked with Victor about this and radio is not going to be implement, at least for the moment.

**Comment by carloslancha** [comment]
Merged, thx!

**Pull request merged**
