### PR TITLE
Update browserslist-config on the generator

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @matuzalemsteles we're using alpha.3 in the rest of the components, shouldn't be here the same version?

**Comment by matuzalemsteles** [comment]
Hey @carloslancha, Yes, but it seems that the current version of `browserslist-config-clay-components` is `alpha.2` I believe it is not accompanying the versions of the components because they do not have a change.

**Comment by jbalsas** [comment]
Versions are automatically released when the package has changes at the time of publication, yes 👍

**Comment by carloslancha** [comment]
Merged, thx!

**Pull request merged**
