### PR TITLE
Feature/a11y

### PR DESCRIPTION
**Pull request by vbence86**
### Intent
To integrate automated accessibility tests to CI.

### Solution
- Adss `metal-a11y-checker` module to execute a11y tests against all clay components. 

### Usage
`npm run a11y`

### CODE REVIEW

**Comment by jbalsas** [comment]
It looks like the tests are passing and not catching any issues, which we know not to be true :)

This is not to be merged until we can see the errors in the components

**Comment by vbence86** [comment]
I'm currently trying to get to the bottom of this. If I wasn't able to identify the issue explicitly, I'll try to get around it with some funky solution.

**Comment by jbalsas** [comment]
hey @vbence86, you forgot to commit the jest snapshots 😉 

@carloslancha, @matuzalemsteles, can you take a look at the changes in https://github.com/metal/metal-clay-components/pull/94/commits/a189053cfad3d1f549d303de189222b0a4400867?

**Comment by matuzalemsteles** [comment]
@jbalsas Sound good!

**Comment by jbalsas** [comment]
Hey @vbence86, sorry about that, but it looks like `yarn.lock` conflicts with the latest changes merged. Could you rebase and resend? Thanks!

**Pull request closed without merging**
