### PR TITLE
Metal Quartz Button: Adds icon alignment

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by robframpton** [comment]
Due to f8abd7353e707302accfe8f6e644f3705ae98d61 this pr needs to be rebased.

**Comment by brunobasto** [comment]
Hey @fernandosouza, can you take care of rebasing this one?

**Comment by fernandosouza** [comment]
Updated @brunobasto

**Review by robframpton — APPROVED** [review]

**Comment by fernandosouza** [comment]
Hey, @brunobasto. I've noticed that this [PR](https://github.com/metal/metal-clay-components/pull/25) from @Robert-Frampton contains part of the implementation I've done here. I have it rebased locally, as soon as Rob allow me, I can update his branch.

**Comment by fernandosouza** [comment]
Resent https://github.com/metal/metal-clay-components/pull/31

**Pull request closed without merging**
