### PR TITLE
Create Metal Quartz Dropdown Component

### PR DESCRIPTION
**Pull request by pat270**
First attempt at Metal Quartz Dropdown

### CODE REVIEW

**Comment by fernandosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robframpton** [comment]
Due to f8abd7353e707302accfe8f6e644f3705ae98d61 this pr needs to be rebased.

**Comment by fernandosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fernandosouza** [comment]
Resent https://github.com/metal/metal-clay-components/pull/38

**Pull request closed without merging**
